# Generated by Django 3.2.21 on 2023-09-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('police_station', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('sender_nic', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('nic', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('recovery_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=20)),
                ('engine_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('license_expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_type', models.CharField(max_length=50)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('nic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.person')),
                ('password', models.CharField(max_length=128)),
                ('license_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('nic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.person')),
                ('password', models.CharField(max_length=128)),
                ('police_station', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('original_image', models.BinaryField()),
                ('vehicle_image', models.BinaryField()),
                ('license_plate_image', models.BinaryField()),
                ('detected_license_plate', models.CharField(max_length=7)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.violationtype')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('vehicle_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.vehicle')),
                ('nic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('due_date', models.DateField()),
                ('payment_status', models.BooleanField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.violationtype')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
    ]
