# Generated by Django 3.2.21 on 2023-10-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230911_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion', models.CharField(max_length=5000)),
            ],
        ),
    ]
