# Generated by Django 4.2.5 on 2023-10-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20231012_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='officer_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
