# Generated by Django 4.2.5 on 2023-10-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_policeofficer_officer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('day_shift', models.BooleanField()),
                ('date', models.DateField()),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.policeofficer')),
            ],
        ),
    ]
