# Generated by Django 4.2.5 on 2023-10-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_schedule_day_shift_schedule_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accident')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
