# Generated by Django 4.2.4 on 2023-10-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vehicle_owner_name'),
        ('api', '0012_otpverification'),
    ]

    operations = [
    ]
