# Generated by Django 4.2.5 on 2023-10-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_officerlocation_cameralocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameralocation',
            name='police_station',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='officerlocation',
            name='police_station',
            field=models.CharField(max_length=20),
        ),
    ]
