# Generated by Django 4.2.5 on 2023-10-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_otpverification'),
        ('api', '0014_create_groups'),
    ]

    operations = [
    ]
