# Generated by Django 4.2.5 on 2023-10-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_0012_otpverification_0014_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='police_station',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
